import os
from train_pipeline import run_whisper_finetuning

def main():
    # Define hyperparameters here
    hyperparameters = {
        "dataset_csv": "../dataset/train.csv",  # Generated by the data_pipeline
        "dataset_output_dir": "../dataset",
        "model_name": "openai/whisper-small",
        "language": "Telugu",
        "task": "transcribe",
        "output_dir": "../whisper_telugu_output",
        "lora_r": 16,
        "lora_alpha": 32,
        "lora_dropout": 0.1,
        "batch_size": 8,
        "grad_acc": 2,
        "learning_rate": 1e-4,
        "epochs": 5,
        "warmup_steps": 100,
        "fp16": True,
        "max_target_tokens": 448
    }

    print("==================================================")
    print("Starting Whisper Finetuning with Hyperparameters:")
    for k, v in hyperparameters.items():
        print(f"  {k}: {v}")
    print("==================================================\n")

    # Start the training pipeline
    run_whisper_finetuning(**hyperparameters)

if __name__ == "__main__":
    main()
